# Timeout in seconds that Limine will use before automatically booting.
timeout: 5

# The entry name that will be displayed in the boot menu.
/yggdrasil
    # We use the Limine boot protocol.
    protocol: limine
    resolution: 1280x720x32

    # Path to the kernel to boot. boot():/ represents the partition on which limine.conf is located.
    path: boot():/boot/yggdrasil
